name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  integration_tests:
    name: Build and Test
    runs-on: macos-latest # Check out which xcode to use if updating macos:https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software
    steps:
      - uses: actions/checkout@v1
      - name: Print Xcode version
        run: sudo xcode-select -p
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x" # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - name: Install Gems
        run: bundle install
      - name: Build and Test
        run: bundle exec rake
